import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components/home-layout/sidebar";
import BackupButton from "@/components/home-layout/backup-button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="px-8 py-5  border-b flex justify-between items-center">
          <span className="text-3xl text-primary">Nizamani Farm</span>
          <BackupButton />
        </header>
        <div className="flex">
          <Sidebar />
          <main className="px-5 py-6 space-y-4 grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
